# Uncomment the next line to define a global platform for your project
platform :ios, '9.3'

target 'thesportspool' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  pod 'Branch'
  pod 'Instabug', '~> 7.3.6'
  # Pods for thesportspool

 # target 'thesportspoolTests' do
 #   inherit! :search_paths
    # Pods for testing
 # end

end
